/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OAuthTokenService } from "../oAuthToken.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OAuthTokenCreateInput } from "./OAuthTokenCreateInput";
import { OAuthToken } from "./OAuthToken";
import { OAuthTokenFindManyArgs } from "./OAuthTokenFindManyArgs";
import { OAuthTokenWhereUniqueInput } from "./OAuthTokenWhereUniqueInput";
import { OAuthTokenUpdateInput } from "./OAuthTokenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OAuthTokenControllerBase {
  constructor(
    protected readonly service: OAuthTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OAuthToken })
  @nestAccessControl.UseRoles({
    resource: "OAuthToken",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createOAuthToken(
    @common.Body() data: OAuthTokenCreateInput
  ): Promise<OAuthToken> {
    return await this.service.createOAuthToken({
      data: data,
      select: {
        accessToken: true,
        createdAt: true,
        expiresIn: true,
        id: true,
        refreshToken: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OAuthToken] })
  @ApiNestedQuery(OAuthTokenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OAuthToken",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async oAuthTokens(@common.Req() request: Request): Promise<OAuthToken[]> {
    const args = plainToClass(OAuthTokenFindManyArgs, request.query);
    return this.service.oAuthTokens({
      ...args,
      select: {
        accessToken: true,
        createdAt: true,
        expiresIn: true,
        id: true,
        refreshToken: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OAuthToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OAuthToken",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async oAuthToken(
    @common.Param() params: OAuthTokenWhereUniqueInput
  ): Promise<OAuthToken | null> {
    const result = await this.service.oAuthToken({
      where: params,
      select: {
        accessToken: true,
        createdAt: true,
        expiresIn: true,
        id: true,
        refreshToken: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OAuthToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OAuthToken",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateOAuthToken(
    @common.Param() params: OAuthTokenWhereUniqueInput,
    @common.Body() data: OAuthTokenUpdateInput
  ): Promise<OAuthToken | null> {
    try {
      return await this.service.updateOAuthToken({
        where: params,
        data: data,
        select: {
          accessToken: true,
          createdAt: true,
          expiresIn: true,
          id: true,
          refreshToken: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OAuthToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OAuthToken",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteOAuthToken(
    @common.Param() params: OAuthTokenWhereUniqueInput
  ): Promise<OAuthToken | null> {
    try {
      return await this.service.deleteOAuthToken({
        where: params,
        select: {
          accessToken: true,
          createdAt: true,
          expiresIn: true,
          id: true,
          refreshToken: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
