/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EmailMetadataService } from "../emailMetadata.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmailMetadataCreateInput } from "./EmailMetadataCreateInput";
import { EmailMetadata } from "./EmailMetadata";
import { EmailMetadataFindManyArgs } from "./EmailMetadataFindManyArgs";
import { EmailMetadataWhereUniqueInput } from "./EmailMetadataWhereUniqueInput";
import { EmailMetadataUpdateInput } from "./EmailMetadataUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmailMetadataControllerBase {
  constructor(
    protected readonly service: EmailMetadataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EmailMetadata })
  @nestAccessControl.UseRoles({
    resource: "EmailMetadata",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEmailMetadata(
    @common.Body() data: EmailMetadataCreateInput
  ): Promise<EmailMetadata> {
    return await this.service.createEmailMetadata({
      data: data,
      select: {
        createdAt: true,
        date: true,
        id: true,
        recipient: true,
        sender: true,
        subject: true,
        threadId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EmailMetadata] })
  @ApiNestedQuery(EmailMetadataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EmailMetadata",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emailMetadataItems(
    @common.Req() request: Request
  ): Promise<EmailMetadata[]> {
    const args = plainToClass(EmailMetadataFindManyArgs, request.query);
    return this.service.emailMetadataItems({
      ...args,
      select: {
        createdAt: true,
        date: true,
        id: true,
        recipient: true,
        sender: true,
        subject: true,
        threadId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EmailMetadata })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailMetadata",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emailMetadata(
    @common.Param() params: EmailMetadataWhereUniqueInput
  ): Promise<EmailMetadata | null> {
    const result = await this.service.emailMetadata({
      where: params,
      select: {
        createdAt: true,
        date: true,
        id: true,
        recipient: true,
        sender: true,
        subject: true,
        threadId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EmailMetadata })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailMetadata",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEmailMetadata(
    @common.Param() params: EmailMetadataWhereUniqueInput,
    @common.Body() data: EmailMetadataUpdateInput
  ): Promise<EmailMetadata | null> {
    try {
      return await this.service.updateEmailMetadata({
        where: params,
        data: data,
        select: {
          createdAt: true,
          date: true,
          id: true,
          recipient: true,
          sender: true,
          subject: true,
          threadId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EmailMetadata })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailMetadata",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEmailMetadata(
    @common.Param() params: EmailMetadataWhereUniqueInput
  ): Promise<EmailMetadata | null> {
    try {
      return await this.service.deleteEmailMetadata({
        where: params,
        select: {
          createdAt: true,
          date: true,
          id: true,
          recipient: true,
          sender: true,
          subject: true,
          threadId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
